name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/eyetowers/*
      CR_PAT: ${{ secrets.CR_PAT }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod

      - name: Credentials
        run: git config --global url.https://$CR_PAT@github.com/.insteadOf https://github.com/

      - name: Lint
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run --timeout=180s

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...