name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: go-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up Go
        uses: actions/setup-go@v6.2.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.8.0
          args: --timeout=180s

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
